---

- name: SSH_VTY_ACL
  connection: network_cli
  gather_facts: false
  hosts: CISCO

  tasks: 
    - name: CREATE SSH_VTY_ACL
      cisco.ios.ios_acls:
        config:
        - afi: ipv4
          acls:
          - name: SSH_ACCESS
            acl_type: standard
            aces:
            - grant: permit
              source:
                address: 192.168.1.0
                wildcard_bits: 0.0.0.255
           
            - grant: permit
              source:
                address: 10.0.4.96
                wildcard_bits: 0.0.0.31

    - name: PLACE SSH ACL ON VTY LINES 0 4
      cisco.ios.ios_config:
        lines:
        - access-class SSH_ACCESS in
        parents: line vty 0 4