---

- name: BLOCK RFC 1918 PRIVATE ADDRESS SPACE
  connection: network_cli
  gather_facts: false
  hosts: ISP

  tasks:
  - name: BLOCK RFC 1918 PRIVATE ADDRESS SPACE ON ISP
    cisco.ios.ios_acls:
      config:
      - afi: ipv4
        acls:
        - name: RFC_1918
          acl_type: standard
          aces:
          - grant: deny
            source:
              address: 10.0.0.0
              wildcard_bits: 0.255.255.255
           
          - grant: deny
            source:
              address: 172.16.0.0
              wildcard_bits: 0.15.255.255

          - grant: deny
            source:
              address: 192.168.0.0
              wildcard_bits: 0.0.255.255

          - grant: permit
            source:
              any: "true"
            

  - name: PLACE RFC_1918 ACL
    cisco.ios.ios_config:
      lines:
      - ip access-group RFC_1918 in
      parents: interface GigabitEthernet0/0
