---

- name: CONFIGURE GROUP POLICY
  hosts: TRNG-RNKSS-DC01
  become_method: runas
  become: yes
  become_user: rnkss\administrator
  
  
  tasks:
  
    - name: DEFAULT DOMAIN POLICY
      ansible.windows.win_powershell:
        script: |
          Set-ADDefaultDomainPasswordPolicy -Identity rnkss.hmsturing.navy.mil.uk -PasswordHistoryCount 3 -LockoutObservationWindow 00:02 -LockoutThreshold 5 -ComplexityEnabled 1 -MinPasswordLength 6 -LockoutDuration 00:02 -MaxPasswordAge 180:00:00:00 -MinPasswordAge 01:00:00:00
    
    - name: IMPORT GPO'S
      ansible.windows.win_powershell:
        script: |
          import-gpo -BackupId F8C6F2F8-1AA8-46A2-A526-473389B606FF -TargetName install_google_chrome_enterprise -path \\Trng-rnkss-af01\gpo$\ -CreateIfNeeded 
          import-gpo -BackupId B4622FCC-72E7-4B49-BE64-963701EFDD1E -TargetName wallpaper_gun -path \\Trng-rnkss-af01\gpo$\ -CreateIfNeeded 
          import-gpo -BackupId ECD60A1A-35C9-4CCD-BD3C-CAB3CBA359AD -TargetName config_logs_maps -path \\Trng-rnkss-af01\gpo$\ -CreateIfNeeded 
          import-gpo -BackupId 5A8A8183-841B-41AF-A338-99AAFFBA9B4D -TargetName config_war_maps -path \\Trng-rnkss-af01\gpo$\ -CreateIfNeeded
          import-gpo -BackupId FFE490BB-4917-4A6F-BB35-7CF4473890F3 -TargetName Int_logon_msg -path \\Trng-rnkss-af01\gpo$\ -CreateIfNeeded
          import-gpo -BackupId D078BE7B-AA1D-470C-B740-73573CDC772B -TargetName user_lastlogonremove -path \\Trng-rnkss-af01\gpo$\ -CreateIfNeeded 
          import-gpo -BackupId 13C52EAE-AEA9-49AA-8976-5C7D7E40D8DB -TargetName config_command_maps -path \\Trng-rnkss-af01\gpo$\ -CreateIfNeeded
          import-gpo -BackupId 27793F6A-B736-4B95-8B20-A908E7920488 -TargetName config_rnkss_visual_brand_package -path \\Trng-rnkss-af01\gpo$\ -CreateIfNeeded 
          import-gpo -BackupId B514D9C3-4AA0-46CD-BE44-DD62858A21A7 -TargetName wallpaper_bomber -path \\Trng-rnkss-af01\gpo$\ -CreateIfNeeded
          import-gpo -BackupId C577F601-990C-400F-BCB0-D9F2FDCA813F -TargetName install_adobe_acrobat -path \\Trng-rnkss-af01\gpo$\ -CreateIfNeeded 
          import-gpo -BackupId 09597CF3-FA28-4994-8FE9-8B148DCE0DC5 -TargetName install_7zip -path \\Trng-rnkss-af01\gpo$\ -CreateIfNeeded 
          import-gpo -BackupId 0D867F35-5F05-4F9D-9414-4335AEE0A45F -TargetName config_cis_maps -path \\Trng-rnkss-af01\gpo$\ -CreateIfNeeded
          import-gpo -BackupId D11402C0-72AE-4562-96D1-BC7142DA7694 -TargetName install_putty -path \\Trng-rnkss-af01\gpo$\ -CreateIfNeeded
          import-gpo -BackupId C45C2350-6353-42DB-B2D0-303623E82D3A -TargetName user_restrict_cpanel -path \\Trng-rnkss-af01\gpo$\ -CreateIfNeeded
          import-gpo -BackupId CFA9C93D-E157-408B-8338-13763C4149FE -TargetName config_engineering_maps -path \\Trng-rnkss-af01\gpo$\ -CreateIfNeeded

            
    - name: GPO LINKS
      ansible.windows.win_powershell:
        script: | 
          New-GPLink -Name "Int_logon_msg" -Target "DC=rnkss,DC=hmsturing,DC=navy,DC=mil,DC=uk"
          New-GPLink -Name "user_lastlogonremove" -Target "DC=rnkss,DC=hmsturing,DC=navy,DC=mil,DC=uk" 
          New-GPLink -Name "config_rnkss_visual_brand_package" -Target "dc=rnkss,dc=hmsturing,dc=navy,dc=mil,dc=uk"
          New-GPLink -Name "wallpaper_gun" -Target "dc=rnkss,dc=hmsturing,dc=navy,dc=mil,dc=uk"

          New-GPLink -Name "user_restrict_cpanel" -Target "OU=COMMAND,dc=rnkss,dc=hmsturing,dc=navy,dc=mil,dc=uk"
          New-GPLink -Name "user_restrict_cpanel" -Target "OU=ENGINEERING,DC=rnkss,DC=hmsturing,DC=navy,DC=mil,DC=uk"
          New-GPLink -Name "user_restrict_cpanel" -Target "OU=LOGISTICS,DC=rnkss,DC=hmsturing,DC=navy,DC=mil,DC=uk"
          New-GPLink -Name "user_restrict_cpanel" -Target "OU=WARFARE,DC=rnkss,DC=hmsturing,DC=navy,DC=mil,DC=uk"

          New-GPLink -Name "install_google_chrome_enterprise" -Target "OU=COMMAND,dc=rnkss,dc=hmsturing,dc=navy,dc=mil,dc=uk"
          New-GPLink -Name "install_google_chrome_enterprise" -Target "OU=ENGINEERING,DC=rnkss,DC=hmsturing,DC=navy,DC=mil,DC=uk"
          New-GPLink -Name "install_google_chrome_enterprise" -Target "OU=LOGISTICS,DC=rnkss,DC=hmsturing,DC=navy,DC=mil,DC=uk"
          New-GPLink -Name "install_google_chrome_enterprise" -Target "OU=WARFARE,DC=rnkss,DC=hmsturing,DC=navy,DC=mil,DC=uk"

          New-GPLink -Name "install_7zip" -Target "ou=COMMAND,dc=rnkss,dc=hmsturing,dc=navy,dc=mil,dc=uk"
          New-GPLink -Name "install_7zip" -Target "OU=ENGINEERING,DC=rnkss,DC=hmsturing,DC=navy,DC=mil,DC=uk"
          New-GPLink -Name "install_7zip" -Target "OU=LOGISTICS,DC=rnkss,DC=hmsturing,DC=navy,DC=mil,DC=uk"
          New-GPLink -Name "install_7zip" -Target "OU=SPECIAL,DC=rnkss,DC=hmsturing,DC=navy,DC=mil,DC=uk"
          New-GPLink -Name "install_7zip" -Target "OU=WARFARE,DC=rnkss,DC=hmsturing,DC=navy,DC=mil,DC=uk"

          New-GPLink -Name "install_adobe_acrobat" -Target "ou=COMMAND,dc=rnkss,dc=hmsturing,dc=navy,dc=mil,dc=uk"
          New-GPLink -Name "install_adobe_acrobat" -Target "OU=ENGINEERING,DC=rnkss,DC=hmsturing,DC=navy,DC=mil,DC=uk"
          New-GPLink -Name "install_adobe_acrobat" -Target "OU=LOGISTICS,DC=rnkss,DC=hmsturing,DC=navy,DC=mil,DC=uk"
          New-GPLink -Name "install_adobe_acrobat" -Target "OU=SPECIAL,DC=rnkss,DC=hmsturing,DC=navy,DC=mil,DC=uk"
          New-GPLink -Name "install_adobe_acrobat" -Target "OU=WARFARE,DC=rnkss,DC=hmsturing,DC=navy,DC=mil,DC=uk"

          New-GPLink -Name "config_war_maps" -Target "OU=WARFARE,DC=rnkss,DC=hmsturing,DC=navy,DC=mil,DC=uk"
          New-GPLink -Name "config_logs_maps" -Target "OU=LOGISTICS,DC=rnkss,DC=hmsturing,DC=navy,DC=mil,DC=uk"
          New-GPLink -Name "config_engineering_maps" -Target "OU=ENGINEERING,DC=rnkss,DC=hmsturing,DC=navy,DC=mil,DC=uk"
          New-GPLink -Name "config_command_maps" -Target "OU=COMMAND,dc=rnkss,dc=hmsturing,dc=navy,dc=mil,dc=uk"
          New-GPLink -Name "config_cis_maps" -Target "OU=CIS,OU=ENGINEERING,dc=rnkss,dc=hmsturing,dc=navy,dc=mil,dc=uk"

          New-GPLink -Name "install_putty" -Target "OU=CIS,OU=ENGINEERING,dc=rnkss,dc=hmsturing,dc=navy,dc=mil,dc=uk" 
          New-GPLink -Name "wallpaper_bomber" -Target "OU=CIS,OU=ENGINEERING,dc=rnkss,dc=hmsturing,dc=navy,dc=mil,dc=uk"
    



      
         
          
          
          
    
