---

- name: CREATE USERS
  hosts: TRNG-RNKSS-DC01
  become_method: runas
  become: yes
  become_user: rnkss\administrator

  tasks:          
    - name: CREATE HOME DRIVES
      ansible.windows.win_powershell:
        script: |
    
          Get-ADUser -filter {ObjectClass -eq "user" } | foreach-object { md \\TRNG-RNKSS-AF01.rnkss.hmsturing.navy.mil.uk\Home$\$($_.SamAccountName) }
          
          $HomeFolders = Get-ChildItem -Path \\TRNG-RNKSS-AF01.rnkss.hmsturing.navy.mil.uk\Home$\ |where{$_.PSIsContainer -eq 'TRue'}
          foreach ($HomeFolder in $HomeFolders) {
          $Path = $HomeFolder.FullName
          $Acl = (Get-Item $Path).GetAccessControl('Access')
          $Username = $HomeFolder.Name
          $Ar = New-Object System.Security.AccessControl.FileSystemAccessRule($Username, 'Modify','ContainerInherit,ObjectInherit', 'None', 'Allow')
          $Acl.SetAccessRule($Ar)
          $Acl.SetAccessRuleProtection($true,$false)
          Set-Acl -path $Path -AclObject $Acl
          }
              
          Get-ADUser -filter { ObjectClass -eq "user" } | foreach-object { md \\TRNG-RNKSS-AF01.rnkss.hmsturing.navy.mil.uk\Home$\$($_.SamAccountName) }
          
          $HomeFolders = Get-ChildItem -Path \\TRNG-RNKSS-AF01.rnkss.hmsturing.navy.mil.uk\Home$\ |where{$_.PSIsContainer -eq 'TRue'}
          foreach ($HomeFolder in $HomeFolders) {
          $Path = $HomeFolder.FullName
          $Acl = (Get-Item $Path).GetAccessControl('Access')
          $Username = $HomeFolder.Name
          $Ar = New-Object System.Security.AccessControl.FileSystemAccessRule($Username, 'Modify','ContainerInherit,ObjectInherit', 'None', 'Allow')
          $Acl.SetAccessRule($Ar)
          $Acl.SetAccessRuleProtection($true,$false)
          Set-Acl -path $Path -AclObject $Acl
          }
              

