---

- name: STORAGE POOL
  hosts: TRNG-RNKSS-AF01
  
  tasks:

    - name: CREATE POOL, VIRTUAL DISK AND VOLUMES
      ansible.windows.win_powershell:
        script: |
          # create a new storage pool
          New-StoragePool -FriendlyName TURING_POOL_1 -StorageSubSystemUniqueId (Get-StorageSubSystem).UniqueId -PhysicalDisks (Get-PhysicalDisk -CanPool $true)

          # create virtual disk
          New-VirtualDisk -FriendlyName TURING_VD_1 -StoragePoolFriendlyName TURING_POOL_1 -Size 100GB -ProvisioningType Thin -ResiliencySettingName Parity

          # initialize underlying physical disks
          Initialize-Disk -VirtualDisk (Get-VirtualDisk -FriendlyName TURING_VD_1)

          # partition and format volumes from virtual disk
          $vd = Get-VirtualDisk -FriendlyName TURING_VD_1 | Get-Disk

          # bring the disk online
          Get-VirtualDisk -FriendlyName TURING_VD_1 | Get-Disk | Set-Disk -IsOffline $false

          $vd | 
            New-Partition -Size 1GB -Driveletter F | 
              Format-Volume -FileSystem NTFS -AllocationUnitSize 4096 -NewFileSystemLabel "DATA"

          $vd |     
            New-Partition -Size 1GB -Driveletter K | 
              Format-Volume -FileSystem NTFS -AllocationUnitSize 4096 -NewFileSystemLabel "USER_DATA"

          $vd | 
            New-Partition -Size 1GB -Driveletter T | 
              Format-Volume -FileSystem NTFS -AllocationUnitSize 4096 -NewFileSystemLabel "APPS"

          
